### ISSUE TITLE
[Self-Hosted]: Wrong Support Email in Login Screen

### ISSUE THREAD

**Issue by idoodler** [oss-apps/split-pro#106]
I am self-hosting this awesome project, I did setup the ENV `FEEDBACK_EMAIL` , it also works when sending a feedback, but I noticed that the feedback Email in the Login Screen is still hard coded.

This is a rather small thing, but it still buggs me^^

I tried to fix it myself, but I think it would break the existing variable as it needs to be renamed as seen [here](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser)

![ksnip_20240918-213115](https://github.com/user-attachments/assets/8446e874-5647-4e9d-a85d-0ec0e301c6cb)

**Comment by KMKoushik** [comment]
we should get the env in the [server props](https://github.com/oss-apps/split-pro/blob/main/src/pages/auth/signin.tsx#L181) and pass it to the compoennt
