### ISSUE TITLE
Edit expense

### ISSUE THREAD

**Issue by KMKoushik** [oss-apps/split-pro#115]
Currently users have to delete and create the expense again. Need a way to edit the expense directly.

All the neccesary code is available in this [file](https://github.com/oss-apps/split-pro/blob/main/src/server/api/services/splitService.ts#L193)

**Comment by Striffly** [comment]
One of the key features I'm most looking forward to, can't wait to see its implementation!

**Comment by ptsimon** [comment]
Yes this would be great!!

**Comment by KMKoushik** [comment]
edit expense is now avaialble in [dev.splitpro.app](https://dev.splitpro.app)

you can test this now, i'll we merging this after some tests
