### ISSUE TITLE
Broken Image Links

### ISSUE THREAD

**Issue by ThunderE75** [oss-apps/split-pro#118]
Transaction image link is broken

![EFg3bBdcmL](https://github.com/user-attachments/assets/1937eecf-8f44-4521-8388-c5b0ce3c8ecb)

**Comment by KMKoushik** [comment]
is this in on live or self-hosted?

**Comment by ThunderE75** [comment]
Its the cloud version, that is hosted on https://splitpro.app/

**Comment by ThunderE75** [comment]
Also, can you please add a small icon next to the transaction that has images attached in the "balance" view? 

 The Balance view ⬇️
![uF86bNwOxT](https://github.com/user-attachments/assets/3e4fb956-488f-4bf9-ae24-94e80283a8c9)

**Comment by KMKoushik** [comment]
image issue is fixed now sorry for that. we can track this in different issue
