### ISSUE TITLE
Does split-pro do transitive calculations/simplify debts?

### ISSUE THREAD

**Issue by Neihtq** [oss-apps/split-pro#126]
Hi, thank you for this app!

We've been using it on our last trip and I'm not sure if the costs for each member are calculated transitively/simplify debts?
E.g.:
- Person A owes Person B 10 EUR
- Person B owes Person C 10 EUR
- Hence, Person A owes Person C 5 EUR and the costs between A and B are settled.

**Comment by KMKoushik** [comment]
it doesn't currrently, but yh have plans to do it!

**Comment by KMKoushik** [comment]
duplicate of #58
