### ISSUE TITLE
Add members save button does not do anything?

### ISSUE THREAD

**Issue by alexanderwassbjer** [oss-apps/split-pro#134]
Is it correct that the save button should not do anything?
I accidentally pressed it but nothing happened.

![image](https://github.com/user-attachments/assets/8f47c1fb-5617-4f2c-9d09-a46196c29f3a)

**Comment by KMKoushik** [comment]
that email will be added to the group, and when the other person signup, they will also see the group

<img width="528" alt="Screenshot 2024-10-29 at 6 34 56 am" src="https://github.com/user-attachments/assets/20f54442-1f9a-44d8-be84-2de12ab4684b">

**Comment by KMKoushik** [comment]
yep
