### ISSUE TITLE
Standard currency

### ISSUE THREAD

**Issue by luttman** [oss-apps/split-pro#137]
Hello!

Would it be posible to either in the group or usersetting to get a default currency, as a non usd user i need to change currency every time.

**Comment by KMKoushik** [comment]
@luttman  actually you don't have to set currency everytime, it's just the first time and it always remember your previous selection. it's not happening for you?

**Comment by laur89** [comment]
as of 1.5.3 (as in the current version) it seems to have regressed - always have to set the currency as it defaults to USD with every new expense. 

self hosted, app saved on iOS. 

Edit: after restarting the app it started defaulting to correct currency. Still a bug tho given it didn't kick in from the get go.
