### ISSUE TITLE
Send email invite if expense is added with new user

### ISSUE THREAD

**Issue by KMKoushik** [oss-apps/split-pro#14]

**Comment by anantraghuvanshi** [comment]
Would love to work on this after setting it up locally and understanding the bits

**Comment by anantraghuvanshi** [comment]
![image](https://github.com/oss-apps/split-pro/assets/43936308/81d192c5-06ab-42b6-ae88-5b7e80e89cb3)
I wanted your help in setting up my .env files as I do not understand all the variables used in the .env.example

**Comment by KMKoushik** [comment]
Sorry for not documenting this properly. 

R2 related variables are for uploading receipts to Cloudflare, you can check it [here](https://www.cloudflare.com/en-au/developer-platform/r2). You don't have set it up if you are not going to test this flow. Just use some random values

WEB_PUSH related are push notifications, you can give random variables for this too.

RESEND_API_KEY is used to send email. Can set  a free account [here](https://resend.com/)

**Comment by KMKoushik** [comment]
@anantraghuvanshi Sorry mate, lemme take this one. Some users already started asking about this feature!

**Comment by KMKoushik** [comment]
> Kindly for it. Sincere apologies for not working on this on time. @KMKoushik

All good man1
