### ISSUE TITLE
How to delete friend or group

### ISSUE THREAD

**Issue by m-4984** [oss-apps/split-pro#15]
I added a friend through their e-mail, but since they didn't get notified I also invited them through the group link. Now the app treats them as two separate users although it's the same e-mail address... I would like to remove one of the duplicates, or the whole group (was just a test anyway).
Maybe I'm also just blind and can't find the option, any help is highly appreciated!

**Comment by KMKoushik** [comment]
Hey, are you sure these are the same email address? Can you please send the email details to me at koushik@ossapps.dev?

Regarding deleting the friend or group. Yh, we don't have that option currently. Will work on them and let you know soon.

**Comment by KMKoushik** [comment]
Related #18

**Comment by KMKoushik** [comment]
Related #20

**Comment by KMKoushik** [comment]
@m-4984  This is fixed now. If the group / friends is setteled up you will able to delete group or friend.
