### ISSUE TITLE
Login error when using Sign in with Google in local env

### ISSUE THREAD

**Issue by anantraghuvanshi** [oss-apps/split-pro#21]
Hello, I am trying to login using my google account, but it is showing these below attached errors:
![image](https://github.com/oss-apps/split-pro/assets/43936308/0c33cdc2-14de-4aca-9394-e5d16f3f7d94)

![image](https://github.com/oss-apps/split-pro/assets/43936308/ca0185f8-a6ff-4ddd-9a73-cbad0d4d0529)

**Comment by KMKoushik** [comment]
It's not an issue with the local env. You should properly create a credential app in Google Console to make it work.

Here's the documentation: https://next-auth.js.org/providers/google


<img width="706" alt="Screenshot 2024-03-22 at 7 19 55 am" src="https://github.com/oss-apps/split-pro/assets/24666922/b80c3d0c-7a67-4f9c-bf1d-1247f2e76603">
