### ISSUE TITLE
Changing the plain email to the email entered by the user

### ISSUE THREAD

**Issue by anantraghuvanshi** [oss-apps/split-pro#39]
![image](https://github.com/oss-apps/split-pro/assets/43936308/d3f52bce-4181-4588-b706-99d90117df8c)
I am opening this issue to fix this email text and probably change this to the email entered by the user.
Kindly assign this issue to me @KMKoushik

**Comment by rrajofficial7** [comment]
@anantraghuvanshi can u give me the file location where this code is written?

**Comment by anantraghuvanshi** [comment]
> @anantraghuvanshi can u give me the file location where this code is written?

I think it would be better if you yourself get through the code base and find out where the changes are required @rrajofficial7 because it would help you understand the project structure properly.
