### ISSUE TITLE
Can't add expense to an empty group

### ISSUE THREAD

**Issue by mjneff2** [oss-apps/split-pro#49]
One would expect to be able to add expenses to a group even before others have joined. Currently, you can't save an expense to a group that only includes you. This is presumably due to using `participants.length === 1`  as a conditional for some of this logic in `AddExpensePage.tsx`

Additionally, the "You can only have one group at a time" error message is a bit confusing. Showing red error text makes it seem like I'm currently in a bad state, even though that's not the case when I have one group added.

**Comment by KMKoushik** [comment]
Thank you for raising this. Will fix them by this weekend!

**Comment by KMKoushik** [comment]
@mjneff2 This issue is fixed, but Adding expense to an empty group does nothing. It will just be in activity but since you paid and you owe the full amount it won't affect the balances!

**Comment by KMKoushik** [comment]
@mjneff2 Released btw.
