### ISSUE TITLE
Wrong date displayed on group details page

### ISSUE THREAD

**Issue by kouyk** [oss-apps/split-pro#50]
It is common to backdate transactions and splitpro thankfully allows for that. However, I think how it is displayed currently is counterintuitive, when viewing the transactions within a group, the date displayed on the left column should be the actual date of the transaction. When viewing the transaction details, the added date should be the actual date in which the transaction is added. Currently the two dates are swapped around. 

https://github.com/oss-apps/split-pro/blob/f0aae3f34e576950cba8e6eae8d004e4eafff919/src/pages/groups/%5BgroupId%5D.tsx#L332

https://github.com/oss-apps/split-pro/blob/f0aae3f34e576950cba8e6eae8d004e4eafff919/src/components/Expense/ExpensePage.tsx#L49

Do correct me if my understanding is wrong, really grateful for this alternative to splitwise!

**Comment by KMKoushik** [comment]
You're partially correct here, I think both should be expenseDate. Will update thanks

**Comment by KMKoushik** [comment]
Okay a second thought, we might need both the dates in Expense page. Will work on it!

**Comment by kouyk** [comment]
Yup seems like the transaction date is missing in the details page. Seems like the correct date is displaying on the groups page now, although the sorting appears to be somewhat arbitrary. I think the splitwise behaviour sorts in reverse chronological order by transaction date, then by creation time such that the last added transaction is always on top.

**Comment by KMKoushik** [comment]
@kouyk Released btw!

**Comment by kouyk** [comment]
> It currently uses expense date to sort like splitwise and you can always find the latest transaction in activity screen

The latest transaction does not appear at the top if it is back dated, e.g. currently there is a transaction from yesterday, and today I add a transaction backdated to yesterday, it will not appear at the top.

**Comment by KMKoushik** [comment]
@kouyk I thought Splitwise has similar behaviour! I might be wrong. Will check. Anyway for now you can check activity, it's based on the created date!
