### ISSUE TITLE
Web Push notifications are buggy

### ISSUE THREAD

**Issue by vishwa5854** [oss-apps/split-pro#60]
When I have my laptop browser subscribed and my phone subscribed to notifications on the same account, after some time only the laptop is getting notifications and the phone doesn't. When I unsubscribe on laptop and try, mobile still didn't work.

However I was able to resolve it by unsubscribing and resubscribing on the phone and it started working after that, but nonetheless I feel like web push notifications are a little buggy, sometimes they don't come until I unlock the phone.

**Comment by KMKoushik** [comment]
@vishwa5854 Currently you can subscribe using only one device. Hence the confusion. Last device you subscribed to will be overridden. 

Also which phone you are using? is it iPhone?

**Comment by vishwa5854** [comment]
It's an Android phone, Samsung S23 Ultra.
Are the subscriptions stored in the database but only one subscription is being fetched per person and sent the notification to?

**Comment by KMKoushik** [comment]
We just store one subscriptions for a user now. So this needs to improved

**Comment by KMKoushik** [comment]
closing this for now as it won't be planned anytime soon.
