### ISSUE TITLE
Release on docker hub or elsewhere

### ISSUE THREAD

**Issue by Openhabber** [oss-apps/split-pro#65]
This is so great and does everything I want! THANK YOU!

However, to make updating and deploying easier, Would it be possible to Release a prebuilt Image on dockerhub or ghcr.io? (github)

**Comment by KMKoushik** [comment]
@Openhabber 
This is a great idea. I want to make self hosting easier for sure. I never done this before. Will defenitely look into it. 

Btw, PRs are welcom _/\_

**Comment by Openhabber** [comment]
Im not sure either how exactly.
I guess its just tied to some sort of cicd of the github project and not easily added via PR.

See https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

I think having a simple way to setup via docker is the only way this project is getting used by people

**Comment by Soulplayer** [comment]
I would also like to see this. I’m currently on unraid and I would like to host this app!

**Comment by KMKoushik** [comment]
hello @Soulplayer, thank you for showing interest. i need some help to set this up.

it's actually quite easy. need to setup similar to https://github.com/unsend-dev/unsend/tree/main/docker

lemme know if you can help

**Comment by Soulplayer** [comment]
I don’t know how to build docker images and host these on a hub. I only know how to use them ☹️

**Comment by KMKoushik** [comment]
It's available in docker hub now https://hub.docker.com/r/ossapps/splitpro

docs available here: https://github.com/oss-apps/split-pro/tree/main/docker
