### ISSUE TITLE
[UX] Add group button icon misleading

### ISSUE THREAD

**Issue by devadula-nandan** [oss-apps/split-pro#68]
The add group button icon is kind of misleading, since it has a user icon and + symbol, could confuse the user whether he is adding a user or a group
![image](https://github.com/oss-apps/split-pro/assets/47176249/e310c839-a112-43ee-9943-7916c36af14b)
A simple + icon would suffice.

**Comment by KMKoushik** [comment]
@devadula-nandan thanks for raising this issue, Yep + will be better icon. Would you be open to contribute? If not I'll take this next week
