### ISSUE TITLE
allow users to add custom information to the settle up banner

### ISSUE THREAD

**Issue by brenol** [oss-apps/split-pro#69]
Reasoning: I live in Brazil and the biggest payment method here is PIX. 

PIX has a payment key (SSN, phone number, uuid... you get the idea). One of my main gripes with Splitwise was never being able to finish payments directly from the app, or people have to ask for the key so the transaction can be completed.

I'm not sure how it could be added, but I think in the Settle Up screen it could should a "Pay now" button or something like that, and somehow it gets some information the original user registered in the app. 

Not sure if you already thought about something like that, just bringing the issue.

(By the way, *love* the "Why" section in the readme)

**Comment by KMKoushik** [comment]
@brenol  was thinking about this for some time, it's really hard to implement neatly coz, every country has different things. But adding and showing custom info can be done, users can take that to their payment provider

**Comment by KMKoushik** [comment]
Closing this for now as it's out of scope
