### ISSUE TITLE
add group link to the "Add Members" modal

### ISSUE THREAD

**Issue by brenol** [oss-apps/split-pro#71]
When there's no one, the link is offered in the empty state screen.

![image](https://github.com/oss-apps/split-pro/assets/7342697/5bedbd31-fa90-43c6-849b-9129ef5c9ed3)

![image](https://github.com/oss-apps/split-pro/assets/7342697/18b7b59c-e5a4-4c20-bd93-969ac7f9c037)

However, you can get the link from the "invite" button. Which I think is using the email:// protocol (not sure, didn't look it up).

Perhaps it could be simplified in the "Add Members" and Invite could be removed?

**Comment by KMKoushik** [comment]
@brenol naah, it just looks cute with 3 buttons lol

**Comment by KMKoushik** [comment]
Jus lemme know if you still think it should be this way
