### ISSUE TITLE
Feature Request : Export the transaction between 2 people 

### ISSUE THREAD

**Issue by ThunderE75** [oss-apps/split-pro#73]
An option to export transactions made between people and how they were split in a csv or pdf format

**Comment by KMKoushik** [comment]
we already export transaction of a user and  group, this will be a subset of it.

- We already have a function a route to get expenses with friends [here](https://github.com/oss-apps/split-pro/blob/main/src/server/api/routers/user.ts#L185)
- Just need a frontend changes where we download data in csv format. check this example https://github.com/oss-apps/split-pro/blob/main/src/pages/account.tsx#L34
