### ISSUE TITLE
amd64 images are pushed for arm64 images

### ISSUE THREAD

**Issue by nirmalsunny** [oss-apps/split-pro#77]
Although the GitHub Actions workflow is trying to push arm64 images, only linux/amd64 exists on the Docker Hub (https://hub.docker.com/r/ossapps/splitpro/tags) same as here (https://hub.docker.com/r/ossapps/splitpro-arm64/tags)

![image](https://github.com/user-attachments/assets/d73b54af-5516-4a02-9e7e-e9d0cfc69de7)

**Comment by nirmalsunny** [comment]
Even under the arm specific repo, amd64 īmages are being pushed.

![image](https://github.com/user-attachments/assets/4cd90ea7-f7ee-474b-a978-0717ad9d4d51)

**Comment by KMKoushik** [comment]
fixed this now, all latest tags will have arm64 from now on. good catch thanks
