### ISSUE TITLE
Feature Request: Implement sending Mails over SMTP

### ISSUE THREAD

**Issue by kruemelro** [oss-apps/split-pro#80]
Hi,
i've seen that the nodemailer module is allready installed. So it would be great if its possible to send mails over SMPT, not only unsend. I think its not a big change, but i don't have the skill to do it by my own :-).

Here is the example code from the nodemailer page: [https://nodemailer.com/about/#example](https://nodemailer.com/about/#example)

**Comment by KMKoushik** [comment]
yep should not be hard

**Comment by okainov** [comment]
That's odd that readme already mentions "SMTP", but it's not supported? oO How am I supposed to send emails from self-hosted version then?

**Comment by KMKoushik** [comment]
@okainov can you please point me to the readme? anyway i'm working on it and you'll have it soon

**Comment by okainov** [comment]
@KMKoushik here https://github.com/oss-apps/split-pro/blob/main/docker/README.md?plain=1#L45

And in general the code feels inconsistent, like in [sendMail](https://github.com/oss-apps/split-pro/blob/f119e13970d395b6bf1bb97de78b08f93e7b43ba/src/server/mailer.ts#L5) you rely on `UNSEND_API_KEY` which is never mentioned anywhere, then [below](https://github.com/oss-apps/split-pro/blob/f119e13970d395b6bf1bb97de78b08f93e7b43ba/src/server/mailer.ts#L74) `resend` is mentioned but never actually used...

**Comment by KMKoushik** [comment]
@okainov we used resend before and moved to unsend so you can self-host unsend ifk you want. but i'm currently changing all this so you can use smtp 

i'll let you know once done, docs are slight outdated i need to update it!

**Comment by KMKoushik** [comment]
@okainov @kruemelro SMTP support is added now, available from version v1.2.19: https://hub.docker.com/r/ossapps/splitpro

also env details are added here : https://github.com/oss-apps/split-pro/blob/main/.env.example#L44
