### ISSUE TITLE
How to set up web push in self hosting scenario

### ISSUE THREAD

**Issue by pvieira84** [oss-apps/split-pro#81]
First of all thanks for your work on this software - pretty simple but at the same time quite helpful.

I'm self hosting and trying to configure push notifications.
I've generated the Vapid Keys online (because I was not able to do it through the console) here: https://www.attheminute.com/vapid-key-generator. Then, I've added the following env vars:
      - WEB_PUSH_PRIVATE_KEY -> (with the private key generated)
      - NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY -> (with the public key generated)
      - WEB_PUSH_EMAIL -> (my email)

Still, I don't get any pop up to enable notifications.

Any guidance on this will be appreciated

**Comment by KMKoushik** [comment]
how are selfhosting it actually? docker or docker compose?

**Comment by pvieira84** [comment]
docker compose

**Comment by KMKoushik** [comment]
@pvieira84 this is an issue with next js bundle not including NEXT_PUBLIC variables at run time, i have make some code changes to fix this. will do this over a weekend

**Comment by KMKoushik** [comment]
@pvieira84 fixed this issue, use the latest docker image

changes this `NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY` -> `WEB_PUSH_PUBLIC_KEY`

**Comment by pvieira84** [comment]
Thanks for the swift action
