### ISSUE TITLE
How to delete “friends”?

### ISSUE THREAD

**Issue by TaylorJKing** [oss-apps/split-pro#82]
Really cool app so far. Was testing it out, and made a test group with dummy friends. Now I want to actually use the app with real friends, but I can’t seem to delete these dummy friends? I’ve deleted the test group, but the dummy friends remained. Any way of deleting them? Thanks

**Comment by TaylorJKing** [comment]
Update: Figured it out. You have to go to “Balances”, click on the “friend”, and then there’s a delete/bin button in the top right.

You should think about adding a specific section in settings or elsewhere for managing friends, cause that’s not super intuitive. Thanks.

**Comment by KMKoushik** [comment]
@TaylorJKing thanks for the feedback, i have to work on this local friends a bit, the app is not architectured that way. i'll think about it.

**Comment by TaylorJKing** [comment]
> @TaylorJKing thanks for the feedback, i have to work on this local friends a bit, the app is not architectured that way. i'll think about it.

That’s alright, not the end of the world; would just be a nice feature. Using dummy emails for now is fine.

**Comment by KMKoushik** [comment]
it's actually a problem for splitpro personally, cuz it tries to send email it bounces. so i'm goin to figure out a way soon
