### ISSUE TITLE
Feature request: web app

### ISSUE THREAD

**Issue by livingsilver94** [oss-apps/split-pro#85]
A web app would enable smartphones to mimick a real native application without the effort to develop an actual app. For example, see [Firefox on Android](https://support.mozilla.org/en-US/kb/use-web-apps-firefox-android). SplitPro is a simple enough service that sounds like the perfect candidate for such a solution.

**Comment by kruemelro** [comment]
I think it's already working as a PWA (Progressive Web App)
- Navigate with your mobile browser to the Site
- Hit the Options Button of your browser 
- Hit "Add to Homescreen"
You get a nice looking App Icon. And it all looks like a native App

**Comment by KMKoushik** [comment]
pwa is supported like @kruemelro mentioned. 

also if you install as pwa you will also able to receive push notifications.

**Comment by okainov** [comment]
Does it work properly offline (without any internet)?

**Comment by KMKoushik** [comment]
nope, can't do offiline stuff!
