### ISSUE TITLE
Add details how to get GOOGLE_CLIENT_ID

### ISSUE THREAD

**Issue by okainov** [oss-apps/split-pro#91]
README does not mention how is one supposed to get the `GOOGLE_CLIENT_ID` var, and it seems required to run (otherwise Docker compose does not start)...

Please add more info there.

**Comment by KMKoushik** [comment]
that's my bad, added in .env.example now. also can check here https://next-auth.js.org/providers/google

this will not be necessary in future as i'm going to make this optional and ability to choose between google / email auth
