### ISSUE TITLE
How to set up R2 storage in self hosting scenario

### ISSUE THREAD

**Issue by pvieira84** [oss-apps/split-pro#92]
I'm self hosting (docker compose) and trying to enable attachments via R2.
I've created the R2 bucket and the API key as follows:
<img width="961" alt="image" src="https://github.com/user-attachments/assets/0fa654a0-aa37-4536-b766-4e90a12ed564">

Then, I've added the following env vars:
- R2_ACCESS_KEY -> (from API Key)
- R2_SECRET_KEY -> (from API Key)
- R2_BUCKET -> (R2 bucket name)
- R2_URL -> (S3 API URL)
- NEXT_PUBLIC_R2_PUBLIC_URL -> (URL for my self hosted splitpro app)

Still, I don't get any option to attach a file.

Any guidance on this will be appreciated

**Comment by KMKoushik** [comment]
hello, are you using the latest version of the splitpro? also are you using docker compose from the repo

**Comment by pvieira84** [comment]
Yes and yes

**Comment by KMKoushik** [comment]
ah weird, lemme test this in local

**Comment by KMKoushik** [comment]
@pvieira84 This is released now. Use the latest docker container now.

NEXT_PUBLIC_R2_PUBLIC_URL is changed to R2_PUBLIC_URL now. check here how to configure them https://github.com/oss-apps/split-pro/blob/main/.env.example#L43

also lemme know if you need updates on splitpro releases. I can add you to the self-hoster mailing list. More context here: https://github.com/oss-apps/split-pro/discussions/93

**Comment by pvieira84** [comment]
@KMKoushik thanks. You can add me to the mailing list.

**Comment by KMKoushik** [comment]
@pvieira84 can you send your email id to hello@ossapps.dev
