### ISSUE TITLE
Feature request: Unselect all when adding expense

### ISSUE THREAD

**Issue by jaclavij** [oss-apps/split-pro#96]
Hi, I recently started using split-pro, migrating from Tricount with a large group of 15 people.

It would be helpful to have an "Unselect all" button/icon when adding an expense in the SplitEqualSection, since we usually have expenses that only affect 2-5 people. Thus avoiding having to manually unselect 10 people, saving clicks.

I guess it also makes sense that it turns into "Select all" after unselecting.

PS: Thank you for this great app!

**Comment by jaclavij** [comment]
I have started to work on this @KMKoushik

**Comment by KMKoushik** [comment]
legend! thank you!
